name: Build and push Docker images

on:
  schedule:
  - cron: '0 7 * * *'
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip Upstream Source Code
        run: |
          curl -OL https://github.com/lsky-org/lsky-pro/archive/refs/heads/master.zip
          unzip *.zip
          mv ./lsky-pro-master/* ./
          mv ./lsky-pro-master/.env.example ./
          rm -rf master.zip lsky-pro-master

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
        
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry 
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/lsky-pro:latest
          platforms: linux/amd64,linux/arm64
